### ISSUE TITLE
Check Vue Example

### ISSUE THREAD

**Issue by gentritabazi01** [adminkit/adminkit#100]
https://github.com/gentritabazi01/AdminKit-Vue-Example

**Comment by paullaros** [comment]
Looks neat! What are your goals with the project?

**Comment by gentritabazi01** [comment]
Just to use AdminKit Easy in **Vue Js**, Can you add on read me as sample project please ?

**Comment by paullaros** [comment]
I'm afraid we can't do that at this moment as the project isn't created or maintained by AdminKit. I'm happy to give you a retweet though. [Send me a DM](https://twitter.com/paullaros).
