### ISSUE TITLE
Dropdown appears below content instead of attached to top element (Mobile)

### ISSUE THREAD

**Issue by tacman** [adminkit/adminkit#108]
![image](https://user-images.githubusercontent.com/619585/123791291-3f6d4680-d8ad-11eb-8a5c-f0c67220d9c9.png)

To reproduce, browse in a mobile viewer and go to https://demo.adminkit.io/pages-clients.html

Scroll down to Angela Ramos and click on the three dots:

![image](https://user-images.githubusercontent.com/619585/123791522-8bb88680-d8ad-11eb-87e4-04ad15ef7f89.png)

The menu should appear there, instead it's below the rest of the content.

**Comment by trasherdk** [comment]
Screen size below 768 :smiley: 
768px and above is okay.
![image](https://user-images.githubusercontent.com/5003891/123922710-81cc7b80-d9b2-11eb-91c3-7c94a0d71f49.png)

**Comment by paullaros** [comment]
Resolved in #113
