### ISSUE TITLE
Alerts missing

### ISSUE THREAD

**Issue by deanpcmad** [adminkit/adminkit#111]
I can see that UI alerts are listed in [the demo](https://demo.adminkit.io/ui-alerts.html), but adding the CSS to my application, the `.alert` classes are not present.

**Comment by paullaros** [comment]
Hey Dean, the [alert](https://adminkit.io/docs/components/alerts/) component is only available in the [pro version](https://adminkit.io/pricing/). Closing this issue for now, if you have any questions, please shoot us an email at [support@adminkit.io](mailto:support@adminkit.io).
