### ISSUE TITLE
Can't use links in top navbar's notification dropdown

### ISSUE THREAD

**Issue by WadeShuler** [adminkit/adminkit#119]
The system dropdown notifications (on the top navbar) break when inserting a link.

```php
<a href="#" class="list-group-item">
    <div class="row g-0 align-items-center">
        <div class="col-2">
            <i class="text-primary" data-feather="info"></i>
        </div>
        <div class="col-10">
            <div class="text-dark">System Notification</div>
            <div class="text-muted small mt-1">This is a test notification...</div>
            <div class="text-muted small mt-1">4 hours ago</div>
            <div class="text-muted small mt-1"><a href="#">mark as read</a></div>
        </div>
    </div>
</a>
```

It seems like some javascript is going crazy here because it grabs the `list-group-item` link tag and repeats it multiple times on it's own.. No, I didn't duplicate it and mess up the HTML, it automatically is grabbing it and inserting the link in there. When I remove the link tag from `mark as read`, it works fine.

<img width="1440" alt="Screen Shot 2022-01-28 at 1 50 06 AM" src="https://user-images.githubusercontent.com/9557392/151501403-8d9dce93-f5ba-4bf7-b911-0fba83f59b0a.png">

**Comment by paullaros** [comment]
Hey Wade, thanks for opening an issue. It looks like you're trying to nest an anchor element within an anchor element.

We commend using stretched links instead: https://getbootstrap.com/docs/5.0/helpers/stretched-link/

**Comment by WadeShuler** [comment]
No, your template is broken and has a BUG.

Take 30 seconds and add a link like I did, and you will see.

```html
<a href="#" class="list-group-item">
    <div class="row g-0 align-items-center">
        <div class="col-2">
            <i class="text-danger" data-feather="alert-circle"></i>
        </div>
        <div class="col-10">
            <div class="text-dark">Update completed</div>
            <div class="text-muted small mt-1">Restart server 12 to complete the update.</div>
            <div class="text-muted small mt-1">30m ago</div>
            <div class="text-muted small mt-1"><a href="#">mark as read</a></div>
        </div>
    </div>
</a>
```

The javascript goes crazy and puts `<a href="#" class="list-group-item"></a>` all over the place multiple times. I DID NOT write the code like that. I simply added a link in the notification as you can see in my screenshot that shows my code. I didn't break the html code. Your javascript is broken.

<img width="1440" alt="Screen Shot 2022-01-28 at 10 09 07 AM" src="https://user-images.githubusercontent.com/9557392/151572846-0d104884-a519-47d3-8d68-79c5a28706c5.png">
<img width="1440" alt="Screen Shot 2022-01-28 at 10 13 49 AM" src="https://user-images.githubusercontent.com/9557392/151572858-4aa899fb-88d7-45e3-a9eb-bd1e1447259d.png">

Not everyone who posts an issue on Github is a noob. I didn't pay $60 to fix the javascript myself.

**Comment by WadeShuler** [comment]
I forgot to show that I tried with `stretched-link` and it does the same thing:

<img width="1440" alt="Screen Shot 2022-01-28 at 10 32 26 AM" src="https://user-images.githubusercontent.com/9557392/151575618-c9e1b675-3147-40cd-a710-7a8d32a08a16.png">

**Comment by WadeShuler** [comment]
Wow... Maybe I shouldn't code while being sick :( I REALLY should have caught the link tag in the link tag... wth

I'm passing data through multiple Laravel components and 1/2 a brain right now.

Sorry for the issue.
