### ISSUE TITLE
app.js throws console error when opening a collapsible menu item

### ISSUE THREAD

**Issue by casually-creative** [adminkit/adminkit#120]
## Current Behavior 😯

When I open a menu item as a user, a console error shows up in DevTools.

## Expected Behavior 🤔

No console error shows up.

## Steps to Reproduce 🕹

1. Open a collapsible menu item.

## Your Environment 🌎

- Browser: Chrome (v97.0.4692.99)
- OS: Windows 10
- Screen size: 1920x1080

## Screenshots 📷

HTML of the item being clicked:
![image](https://user-images.githubusercontent.com/5587999/151991918-788db224-0667-4d1a-83ff-8abe91c0bc2f.png)

Console error:
![image](https://user-images.githubusercontent.com/5587999/151991450-ec2aa243-44b2-498e-a99e-a023c215e29a.png)

Javascript line that throws the error:
![image](https://user-images.githubusercontent.com/5587999/151991368-dd2dec4f-a9d0-4614-a827-6bfcdd59ea0d.png)

**Comment by paullaros** [comment]
I haven't been able to reproduce this error (using W10 and Chrome v97.0.4692.99). As this concerns the Pro version, could you create a zip file with the error and email us at support@bootlab.io? Closing this issue for now.
