### ISSUE TITLE
Disabled buttons overlap with input when in an input-group

### ISSUE THREAD

**Issue by casually-creative** [adminkit/adminkit#124]
When using an input-group with a disabled button, the border of the input overlaps with the button because the button is set to `opacity: 0.65` and `margin-left: -1px`

## Current Behavior 😯

A border overlaps.

## Expected Behavior 🤔

The border shouldn't overlap.

## Steps to Reproduce 🕹

Use the following HTML:

```html
<form method="post">
    <div class="input-group">
        <input class="form-control" type="text">
        <button type="submit" class="btn btn-danger" disabled>Delete</button>
    </div>
</form>
```

## Screenshots 📷

![image](https://user-images.githubusercontent.com/5587999/166557523-2ec118cc-79e7-4aad-a8a6-6c5d7db4c79c.png)

**Comment by paullaros** [comment]
This looks like an issue related to the Bootstrap framework. I'm closing this issue here.
