### ISSUE TITLE
Alert is showing every page  "mil"

### ISSUE THREAD

**Issue by IT222222** [adminkit/adminkit#125]
After integrating adminkit to my project, an alert which has "mil" is showing every page.
I searched it on a code,  like this alert("mil"), but there is no result,

**Comment by paullaros** [comment]
It is very hard to predict the cause of the error without log files, knowing your environment, screenshots, understanding what you're trying to achieve or which steps you took.

Please fill in the [issue template](https://github.com/adminkit/adminkit/issues/new?assignees=&labels=bug&template=bug_report.md) when creating an issue. This issue will be closed.
