### ISSUE TITLE
When clicking on a table TH it suddenly re-orders.

### ISSUE THREAD

**Issue by bedrijfsportaal** [adminkit/adminkit#128]
## Current Behavior 😯
I've generated a table with th and td tags, and on clicking the th element it suddenly re-order to a-z.
It looks like it will do only if the table has left/right th and td.

## Expected Behavior 🤔
Do nothing on click, never asked this.
Cannot find an example on the demo site

## Steps to Reproduce 🕹

Steps:

1. Create a card with `table` element and use class `table`
2. Setup the code like below.
3. Click on the TH element inside the browser
4. You will see it re-order according to values.

```
<!-- Example HTML -->
<table class="table">
    <tbody>
        <tr>
            <th>Element 1</th>
            <td>Value element 1</td>
        </tr>
        <tr>
            <th>Ascending name</th>
            <td>Value ascending</td>
        </tr>
        <tr>
            <th>Descending name</th>
            <td>value descending</td>
        </tr>
    </tbody>
</table>
```

## Your Environment 🌎

- Browser: Google Chrome 104.0.5112.101
- OS: Windows 10
- Screen size: Different screens/sizes same behavior

## Screenshots 📷
Not available, this can only be checked on active screen

**Comment by paullaros** [comment]
So far I've not been able to re-create the issue. Are you using the free or paid version? And does the same issue occur when you modify the `pages-blank.html` in the [package](https://adminkit.io/#download)?

**Comment by erikkraijenoord** [comment]
I've got a license I paid for, haven't checked on the blank.html does it matter if it's in a card element as well? Will test this and provide some more info.

**Comment by bedrijfsportaal** [comment]
Seems like something else is causing this issue, have no idea what but the theme doesn't seem to be the issue.

**Comment by paullaros** [comment]
Happy to take a look if you can share a live demo URL of your app. Please shoot us a message at [our website](https://adminkit.io/support/). Closing this issue.
