### ISSUE TITLE
AdminKit theme for select2, or another enhanced dropdown library

### ISSUE THREAD

**Issue by casually-creative** [adminkit/adminkit#129]
## Summary 💡

The adminkit library is lacking an official integration with a library that enhances dropdowns, for example [select2](https://select2.org/). A library like that is a crucial component to providing more user friendly forms for the user. If we choose to implement such library on our adminkit themed website, the dropdown's styling does not fit with adminkit. It's a lot of work to manually make it all look neatly integrated. Therefore, it would be very appreciated to have one of those libraries styled for us with the kit.

## Examples 🌈

Straight after dropping in select2:

![image](https://user-images.githubusercontent.com/5587999/187748927-2745fedd-a560-4b62-836a-27d08ff899b9.png)

I still haven't covered all the different select2 configurations, or all the adminkit themes, but this is a nice preview of what it could look like. I did this by manually overwriting some CSS:

![image](https://user-images.githubusercontent.com/5587999/187746153-29c92c39-e360-4968-87ea-e7c415ac7abf.png)

## Motivation 🔦

Searching in a dropdown with a lot of items is easier with a library like select2. They provide a searchbox and also async ajax searching. They also allow multi selects with a pills like visualisation.

**Comment by paullaros** [comment]
The Pro version of AdminKit includes multiple advanced input elements, including a library (Choices.js) that extends the HTML select element. It works with both the light and dark theme. https://demo.adminkit.io/forms-advanced-inputs.html

Ps. if you have any questions about the Pro version of the product, please shoot us an [email](mailto:support@adminkit.io). Closing this issue.

**Comment by casually-creative** [comment]
My bad, somehow I missed this. Thanks!

**Comment by toxpal** [comment]
I know this is old question, but didn't want to create a duplicate. Is select2 supported in Pro version? I use select2 in my projects and don't want to migrate to Choices.js

**Comment by casually-creative** [comment]
@toxpal No it's not. However you can still manually override styles to create the same look. It's quite some work, especially knowing there's a light and dark theme, but doable. I didn't wanna go through the effort so I made the swap to choices.js.
