### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Diegobecker07** [adminkit/adminkit#133]
Hello.
I purchased the adminkit and have been using it in a project for some time, but it has many project dependencies that are out of date. I'm having trouble performing the update, especially for packages that have a major version available, thus having breaking changes when updating.
I would like to know if they could launch a feature with these updates and make them available, at least for those who purchased a license?

I'm sorry for my english.

![Screenshot_8](https://user-images.githubusercontent.com/40552153/224505144-6a298a4b-86c5-4ebe-ba47-ef8d4ac83dfe.png)

**Comment by paullaros** [comment]
Hey @Diegobecker07,

We'll soon upgrade the dependencies to the latest versions. In the mean time, can you try bumping them to the latest minor versions manually?

```sh
npm install npm-check-updates -g
ncu --target minor -u
npm install
```

Ps. as this question seems to be about the pro version, I'm closing this issue. You can send any follow up questions to our support channel. We usually reply within 24h. support@adminkit.io
