### ISSUE TITLE
Private npm package for PRO

### ISSUE THREAD

**Issue by UtechtDustin** [adminkit/adminkit#136]
## Summary 💡
We would love if you could add an private package for the PRO version, currently we have to add the source code of adminkit to our project and build it.   
Maybe there is already one and we don't found the documentation ?   
We only found the package [removed] which is public, so i guess it's not offical :)

## Motivation 🔦
If we have to add adminkit source code to our code we blow up project.   
Also it would be more easier to maintaince the theme, just update the version in the package.json and build it again.

**Comment by paullaros** [comment]
Hi @UtechtDustin, the package you linked is not the official one. Thank you for the suggestion, I will add it to the roadmap. If you have any additional questions regarding the PRO version, please feel free to contact [support@adminkit.io](mailto:support@adminkit.io) in the future. Thank you.
