### ISSUE TITLE
can't open dropdown menu while js is activated

### ISSUE THREAD

**Issue by gzandrk** [adminkit/adminkit#137]
Hi, i tried to apply your template to my project but when i tried to call the js, dropdown menu on header didn't show properly. If I didn't call the js, the dropdown back to normal, but the sidebar toggle can't be clicked and did't show

**Comment by paullaros** [comment]
Can you provide a reproduction project? (e.g. on stackblitz)

Also, make sure to follow the [Starter template](https://adminkit.io/docs/getting-started/quick-start#starter-template)

**Comment by gzandrk** [comment]
hi, I try to follow the Starter Template, but it still didn't work. I think it because i tried to implement it on laravel. I already do npm run build and it already build in my public folder and the output is like this public/build/assets/app-075eb762.js. And when I call it using <script src="{{ asset('/build/assets/app-075eb762.js') }}"></script>, they didn't work out for the js. When I tried to use your CDN, the js is working but the css for dropdown didn't work properly . Can you enlighten me?

**Comment by paullaros** [comment]
If you're able to provide a reproduction project, I'm happy to take a look!

**Comment by gzandrk** [comment]
how to provide my project? Can I invite you to my repositories or I just drop my code here?

**Comment by paullaros** [comment]
Could you shoot us an email at support@adminkit.io, including the code files? I'm closing this issue, as it has most likely something to do with your set-up and not the AdminKit files.
