### ISSUE TITLE
[BUG] - the setting toggle covering the footer nav.

### ISSUE THREAD

**Issue by abhimanyu0018** [adminkit/adminkit#138]
# [BUG] the setting toggle covering the footer nav.

## Describe the bug :
the setting toggle in the bottom right side of the HOME page, is covering the the footer nav menu.

##  how to reproduce the issue :
steps - 
1. Go to The Home page - https://demo.adminkit.io/
2. Scroll down to the bottom.

## Screenshot
![Screenshot 2024-01-11 180047](https://github.com/adminkit/adminkit/assets/66407920/2df71fb7-045a-40b8-8c26-8af79aee0cdb)

**Comment by abhimanyu0018** [comment]
if it is alright with you, I would like to resolve this bug.

**Comment by paullaros** [comment]
As the setting toggle element is provided solely for demonstration purposes, we do not consider it a 'bug'. However, we understand that it may be inconvenient for users who are actively utilizing on it in their production environment. 

This feature is exclusively available in the Pro version, so we are closing this matter. If you wish to relocate the position of the element, you can achieve this by updating the `/src/scss/3-components/_settings.scss` file.
