### ISSUE TITLE
IE 10/11 Issues.

### ISSUE THREAD

**Issue by aadrian** [adminkit/adminkit#5]
Hi,

There seems to be quite a few issues with IE 10/11 :
 - Scrolling is not working in https://demo.adminkit.io/index.html
 - Cards (panels) overlap the footer
 - "Settings and Documentation" right-side bar does not overlap panels, but create a margin
   - it also docks over the scrollbar, unless mouse over, than jumps to the correct position
 - Markdown Editor shows no icons on the toolbar buttons.
 - ApexCharts not rendered at all (empty cards, only titles)

just to mention a few. 

Since TWBS 4.5 **is** IE 10/11 compatible, is there any chance fixing those issues?

Thank you.

**Comment by paullaros** [comment]
Hey Adrian, thanks for opening an issue with us. I will be closing this one, as we don't support IE10 and IE11. We've added a list of the supported browsers to the README.md file for more clarity. Thanks for using AdminKit!
