### ISSUE TITLE
Upgrade to Bootstrap 5 beta 1

### ISSUE THREAD

**Issue by hxmcn** [adminkit/adminkit#72]
Hi, Bootstrap 5 beta 1 already released, please update it,thx!

**Comment by paullaros** [comment]
Hello! You can expect an update in roughly 2~3 weeks.

**Comment by mustafa-online** [comment]
The demo is still using alpha version! Bootstrap released it's beta 2

**Comment by paullaros** [comment]
@mustafa-online AdminKit just got bumped to beta 2
