### ISSUE TITLE
performance improvement

### ISSUE THREAD

**Issue by lesismal** [adminkit/adminkit#78]
I like this template, thanks to your great job!

traditional frontend solutions usually got a mediocre performance, and I am sensitive to that. so I forked this project and transformed it into a single-page application with [pm.js](https://github.com/lesismal/pm) to manage the page content. The performance was greatly improved. If necessary, you can refer to [pm.js](https://github.com/lesismal/pm) and [3rdrepo/adminkit](https://github.com/3rdrepo/adminkit)

**Comment by paullaros** [comment]
Thank you! Glad you're enjoying AdminKit.

While it's not a bad idea, we're trying to keep AdminKit as less opinionated as possible. PM looks great, but could also add an extra layer of friction when integrating with existing frameworks like .NET, Laravel, Django and Rails.

Closing this for now.
