### ISSUE TITLE
babel/traverse, popper installation issues

### ISSUE THREAD

**Issue by tacman** [adminkit/adminkit#86]
git clone .. followed by npm install gives this error:

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@babel/traverse/-/traverse-7.12.17.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@babel/traverse@https://registry.npmjs.org/@babel/traverse/-/traverse-7.12.17.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

Also, a big plus of bootstrap 5 is using popper 2, but it seems that it's trying to install popper 1.

bootstrap 5 beta 2 is out, and they've indicated it's pretty close to final.  Can you bump all the dependencies please?

**Comment by paullaros** [comment]
Hey Tacman, you can expect an update soon. What node + npm version are you using? So far we weren't able to re-create your issue locally. Thanks.

**Comment by tacman** [comment]
```bash
node -v && npm -v
v14.15.1
7.5.3
```

However, it seems to be working now, I must have upgraded something since then, or there was a temporary glitch on that particular package.
