### ISSUE TITLE
Add to YarnPkg.com

### ISSUE THREAD

**Issue by tacman** [adminkit/adminkit#89]
I'd love to be able to install this with 

    yarn add adminkit/adminkit

Alas, it looks like there an old, unrelated adminkit there already.

https://yarnpkg.com/?q=adminkit&p=1

I think this is what will help me, but I'll create another issue that gets more to the core of what I'm confused about.

**Comment by tacman** [comment]
I'm attempting to publish this myself, but had to change the private: true to false in package.json on my fork.  I'll also submit a PR for that here.  Perhaps you can publish this to yarn when you've finished the beta2 integration?

**Comment by paullaros** [comment]
Hey @tacman, we removed the `private` property from the `package.json` file. You should be able to publish it now.
