### ISSUE TITLE
Feature Request: Right side aside (settings panel) in free version

### ISSUE THREAD

**Issue by tacman** [adminkit/adminkit#95]
I'm moving from AdminLTE to AdminKit, and previously used the collapsible settings on the right site as a place for my search form.

![image](https://user-images.githubusercontent.com/619585/109695944-872bcd80-7b5a-11eb-80f7-560bbcc04040.png)

Would you consider adding the icons and structure for the aside like you have in the pro version, but only include the content of that settings panel in pro version?

That is, leave the settings content in pro, but not the settings panel html.

**Comment by paullaros** [comment]
Hello, unfortunately that's not something we're planning to add to the free version. If you need that functionality, please upgrade to [Pro](https://adminkit.io/pricing/).
